### ISSUE TITLE
One UMI shared by two reads simultaneously

### ISSUE THREAD

**Issue by kir1to455** [gaolabtools/scNanoGPS#10]
Hi Cheng-Kai,

I found that barcode.curated.minimap2.bam with one UMI shared by two reads simultaneously.
![image](https://github.com/gaolabtools/scNanoGPS/assets/87375686/56273ce5-e5bf-4468-9f68-e503e3ba4006)

Normally, “The reads that share same UMIs are collapsed to generate consensus sequences of individual molecules using software, SPOA.” If I didn't understand the mistake, there should be no shared UMI reads after the curator.py step. Or if this situation is normal, can both these two reads be used for counting? But the sequences of these two reads are almost the same, and I think it's just due to PCR amplification.
Could you give some advice?

Best wishes,
Kirito

**Comment by shiauck** [comment]
Hi Kirito,

About your question.
You're correct. scNanoGPS use SPOA to collapse PCR duplicates.
To judge whether the reads are PCR duplicates or not, scNanoGPS requires both two criterials: (1) very close genomic coordination (<5 bp) and (2) similar UMI sequence (<= 2LD).
"Reads that map to the same genomic regions (within <5 bp) are grouped into read clusters to achieve batch computing. All reads belonging to the same read clusters and having UMIs within two LDs are considered to be amplified from the same RNA molecules."

In your case, the two duplicates are mapped onto reference genome staring from chr5:1801400 and chr5:1801406.
Because the starting position of the two reads are larger than 5 bp, they are treated separately rather than duplicates.

It's not easy to judge how close is close about the mapping starting position of PCR duplicates.
Sequencing quality and error rate, aligning accuracy, and complexity of the read are affecting the starting position of the alignment.
So that we arbitrarily used this stringent criterion.
I can make a change to let user manually set the range.

Thanks for your feedback.
I really appreciate it.

Regards,
Cheng-Kai
