### ISSUE TITLE
Running isoform quantification when skipping curation step 

### ISSUE THREAD

**Issue by chuckzzzz** [gaolabtools/scNanoGPS#12]
Hi,

Thanks for developing this great tool! I have a quick question regarding the output of `reporter_isoform.py` when curation is skipped. 

First, even though I skipped the curation step, there still are *.curated.minimap2.bam in the temporary directory. Is this the expected behavior? 

Second, after the reporter isoform step successfully finishes, the output table is a bit difficult to interpret. Could you explain the row names and what each individual value means in the matrix? I think the ENST* part is transcript ID but could you clarify?

Here is a screenshot of what it looks like for the first five columns and the first twenty rows.

![image](https://github.com/gaolabtools/scNanoGPS/assets/39171423/250f9913-d45d-4ad1-a7f4-8efdaae9f88a)
 
Thanks so much!
Charles

**Comment by shiauck** [comment]
Hi Charles,

Thank you for using our tool.
The answers for your question:
(1)
Yes, our tool uses "*.curated.minimap2.bam" as suffix no mater the parameter "--skip_curation" is used or not.
So that the following different reporters (expr, isoform, and SNV) can easily locate and use the same ".curated.minimap2.bam" files as input, and users don't need to assign input file names when using reporters and prevent clerical errors.

(2)
Supposedly, the 1st column is a combination of gene symbol and Ensembl transcript ID.
From your screenshot, it seems that the 1st column is combination of "protein ID" and Ensembl transcript ID.
Because the gene symbol is parsed from LIQA result.
Could you check your genome annotation file used for LIQA ?
Mine looks like:
<img width="1272" alt="image" src="https://github.com/gaolabtools/scNanoGPS/assets/19282711/efccd489-a424-4f6c-ab53-848364152d81">
and the LIQA results under "tmp" folder looks like:
<img width="1014" alt="image" src="https://github.com/gaolabtools/scNanoGPS/assets/19282711/a855ce77-3a33-44fe-9168-152f635f2b62">

(3)
The result matrix is quite similar to the expression matrix.
Each row is a transcript (GeneSymbol_TranscriptID), and each column is a single cell barcode.
Inside the matrix the float numbers are the numbers from LIQA result computed from raw read number with EM-algorithm.

Hope this helps.

Regards,
Cheng-Kai
