### ISSUE TITLE
Low quality reads filtering

### ISSUE THREAD

**Issue by chuckzzzz** [gaolabtools/scNanoGPS#16]
Hi, thanks for developing this amazing tool! I have one question regarding the scanner part. 

One of the incentives in using ONT is to profile highly repetitive regions. However, I was not able to find any repeat expansion in the final output alignment files. So I went back to the raw fastq files and extracted reads carrying at least X number of repeats and store them in a separate fastq file. When I try to run scanner on these reads, the log would look something like this. 

```
Parameters for pattern search:
	Length of barcode:             16
	Length of UMI:                 12
	5'-adaptor sequence:           AAGCAGTGGTATCAACGCAGAGTACAT
	3'-adaptor sequence:           CTACACGACGCTCTTCCGATCT
	PolyT sequence:                TTTTTTTTTTTT
	Scanning region length:        100

Penalty for dynamic programming:
	Matching:                      2
	Mismatching:                   -3
	Gap opening:                   -5
	Gap extension:                 -2
	Editing distance:              2

Parameters for computing:
	Number of computer cores:      16
	Number of reads per batch job: 1000
	Minimal length of read:        200
	Matching threshold:            0.7
	Scoring threshold:             0.4

Debug mode switch:             False

Total 717 reads are processed.
Time elapse: 0 : 0 : 0.57
Detecting rate: 0.00%

Result counting:
	Number of 3'-adaptor located on the read head region:           	0
	Number of 3'-adaptor + polyT on the read head region:           	0
	Number of 3'-adaptor located on the read tail region:           	0
	Number of 3'-adaptor + polyT on the read tail region:           	0

Alignment counting:
	Number of 3'-adaptor having no mismatch:                            	0

	Number of 3'-adaptor having mismatch at the last one position:      	0
	Number of 3'-adaptor having mismatch at all the last two position:  	0
	Number of 3'-adaptor having mismatch at all the last three position:	0

	Number of 3'-adaptor having in/del at the last one position:        	0
	Number of 3'-adaptor having in/del at the last two position:        	0
	Number of 3'-adaptor having in/del at the last three position:      	0

	Number of rescued truncated 3'-adaptor on the read head region: 	0
	Number of rescued truncated 3'-adaptor on the read tail region: 	0

Finish time stamp: Mon, 13 Nov 2023 18:39:39
```

Could you elaborate a bit more on how this step works and why none of the reads are retained afterward? These reads are of lower quality score due to the repetitiveness. My guess is because within the 100 bp scanning window of both 5' and 3' we are not getting the barcodes, adaptors etc. due to the low quality so they are not retained. But could you clarify how this works? Thanks!

**Comment by shiauck** [comment]
Hi,

The function of scanner is described as you can see in the paper:
"The raw FASTQ files were processed by scNanoGPS ‘Scanner’ function to scan the expected adapter patterns using the parameters (match: 2, mismatch: −3, gap opening: −5, gap extension: −2, sequence identity 70%) equivalent to NCBI Basic Local Alignment Tool (BLAST) algorithm. Raw reads with an insert length of less than 200 bp was excluded from scanning."

Please refer to the figure 1 in the paper "Schematic diagrams of scNanoRNAseq" for the architecture.
The scanner is designed to find out both 5' and 3' 10X adapters.
That's why you can see the default parameters including 5'-, 3'-adapter sequence, and penalties for matching, mismatching, opening gap, extending gap, and other relatives.

So (1) please make sure that your reads are designed in the same architecture. (2) scanner search 5'/3'-adapters in the first and last 100 bps by default. If you think your reads might contain too long overhang unknown sequence in front of / after the 5' / 3'-adapters, you can try to increase searching region by assigning "--scanning_region 200" to double the search region. (3) you can try debug mode ("--debug_mode 1") to check the detailed alignment if you like.

Hope this helps.

Regards,
Cheng-Kai
