### ISSUE TITLE
Questions on running the example data

### ISSUE THREAD

**Issue by madnessfish** [gaolabtools/scNanoGPS#17]
Thank you for creating such a nice tool! This definitely aid the single-cell long-reads research. I am running the steps in tutorial/ run_scNanoGPS.sh with the example data.

1. The resulted "matrix.tsv" is a gtf-like file without any count information.

Geneid	Chr	Start	End	Strand	Length	gene_name
ENSG00000279973	chr22	11066418	11068174	+	1757	CU104787.1
ENSG00000280341	chr22	15282557	15288670	-	6114	AP000542.3
ENSG00000279442	chr22	15298378	15304556	-	6179	AP000542.2

2. The resulted "matrix_isoform.tsv" is completely empty.

- The resulting log:
reporter_isoform.py -t 20 --liqa_ref example/GRCh38_chr22.liqa.refgene
Output directory:    scNanoGPS_res
Temporary directory: tmp
Reference of LIQA:   example/GRCh38_chr22.liqa.refgene
Batch LIQA spends 0 : 0 : 0.03

Please let me know whether this is normal as the example data is subsampled or I am having some problems in my installation steps.

**Comment by shiauck** [comment]
Hi,

The example data containing in github is just for checking the script executable.
Because of the file size limit, we couldn't subset enough number of read to produce matrix.
So it's normal that you see empty result by running example.

To have a real taste, please download our published data from [GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE212945).
`
Ex:
fastq-dump --gzip GSM6564300
`
Hope this helps.

Regards,
Cheng-Kai

**Comment by madnessfish** [comment]
Thank you so much for your prompt reply! We will run the pipeline directly in our own data and also the published data for trial.
