### ISSUE TITLE
Can I use 10x Cell barcode white lite in Assigner step

### ISSUE THREAD

**Issue by wuy24** [gaolabtools/scNanoGPS#2]
Hi, 
I am running my ONT sngle cell data to the Assignmer step right now. 
Based on our previous illumina data, our capture is about 10000 cells. However, in the assigner.log.txt file the estimated cell number is about 20000 cells. And this step took very long time (I started this step 3 days ago, it is still running). In the log file , it is shown that batch job number is 13814 of 20690 as follows. I wonder is there any way to filter the cell barcode first and then do the assignment , or is it an option that we can use a 10x barcode whitelist as guidence in this step. Or how can I boost the calculation time in this step?
Thank you very much!
<img width="559" alt="image" src="https://user-images.githubusercontent.com/114779622/217034181-1f4edaf8-9fa8-432d-9c2e-bdcadadd0040.png">

Best,
Ying

**Comment by shiauck** [comment]
Hi Ying,

The assigner step is mainly doing the cell barcode curation without any whitelist.
It's a data-driven process, meaning that the more your target cell numbers the longer curation time it requires.
The reason why you see it doubles the number (20,690) of your expected cell number (10,000) is because we let assigner to catch potential barcodes according to slope changing (signal diminishing).
Then it curates the cell barcode with in 2 Levenshtein distance.
After curation, you can check the length of barcode list with "zcat scNanoGPS_res/CB_merged_list.tsv.gz | wc -l".
This can tell you the number of curated cell barcodes.

This process accommodates customized cell barcodes, without 10X whitelist or version.

Thank you for your suggestion.
In our experiments, we only target to around 3,000 cells.
I'll think a way to boost this process in the future version.

Regards,
Cheng-Kai
