### ISSUE TITLE
"edditing_distance" option in scanner.py

### ISSUE THREAD

**Issue by myano-fgin** [gaolabtools/scNanoGPS#23]
Hi Cheng-Kai,

I am sorry to bother you again, but I have other two issues of question and request.
This is the question.

What does the "editing distance" in scanner.py mean?
we are able to set the option.
```
  --editing_distance=ALLOW_EDITING_DISTANCE
                        Editing distance for cell barcode detection. Default: 2
```
ALthough I am able to understand distances in assigner and curator while calcurating them in assiging CB and collasping UMI, It is not clear for me to understand the distance while the scanner process.

I compared the scanner process with default "2", and "0" and "5".  The result in log file about the numbers of reads are same.  No difference between the result of the three settings.

Best regards,
Minoru

**Comment by LilyLuyang** [comment]
Hi Minoru,

I also had this confusion about edit distance before. In my view, the edit distance was set to find the barcode and UMI as accurate as possible in this step since the dynamic programming algorithm is used to perform pairwise alignment between target and query sequences here.  '--editing_distance 2' allows 2 penalties here. The results are the same when you use "2", and "0" and "5" numbers here, which means that output are not influenced by these three different settings.

Hope my understanding is right here, and welcome to communicate each other during the learning process here:)

Thanks,
Lily

**Comment by shiauck** [comment]
Hi,

The editing distance we are using is [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance).
If you are interested in, please refer to number 5 or 8 papers we cited in our paper.
We set it to 2 as default.
There were many paper discussed about the optimal threshold.

If there's no difference when you set distance to "0", probably in your data the adaptor sequences are all perfectly ligated without any chemical manufactured and sequencing error.
Hope this helps.

Regards,
Cheng-Kai

**Comment by myano-fgin** [comment]
Hi Lily, Cheng-Kai,
Thank you for the comments on my question and the explanation about the (Levenshtein) distance.
At this moment, I am going to un-change the option to be the default "2".
In case I think that need to check the correctness of adapter sequences at the scanner process, I will come back to this matter and try to use the option again.
Best regards,
Minoru
