### ISSUE TITLE
Weird behaviour - assigner.py

### ISSUE THREAD

**Issue by davidebolo1993** [gaolabtools/scNanoGPS#3]
Hi,

it seems assigner.py combines somehow the output folder with the input file to look for the barcode list.
Minimal example:

```bash
python3 resources/scNanoGPS/assigner.py -i evaluation/scanner/barcode_list.tsv.gz
```

returns

```
Cannot find Cell barcode list file: scNanoGPS_res/evaluation/scanner/barcode_list.tsv.gz !
```

Workaround is copy the barcode_list.tsv.gz in the output folder and run assigner from the output folder itself - but this is something I don't want to use in the long-term. 

Thx,

Davide

**Comment by shiauck** [comment]
Hi Davide,

When using the assigner parameter "-i", you only need to give "barcode_list.tsv.gz" as default.
Because your working folder is at "evaluation/scanner", please give the folder name with "-o" parameter.
In your case, it could be "-o evaluation/scanner".
Assigner will assemble the two parameters together to fetch the input file from "/evaluation/scanner/barcode_list.tsv.gz"

If you feel like to separate outputs step-by-step, you can consider using symbolic link to play the trick without changing the meta file name but the folder name.

Thank you for feedback.
Cheng-Kai
