### ISSUE TITLE
long curator times

### ISSUE THREAD

**Issue by ebwinter95** [gaolabtools/scNanoGPS#40]
Hi Cheng-Kai,

I am running into very long times (5+ days) when running the curator step, even with increasing the thread count to 80. Is there any interest in adding a parameter that can be set to limit the number of reads that each consensus sequence is made from? 

Thanks for making this pipeline, it works great otherwise!
-Evan

**Comment by shiauck** [comment]
Hi Evan,

Thanks for the feedback.
We've noticed that, in some case, the curator could get stuck because of unexpectedly high read depth of certain genes.
No matter this high read depth is due to natural or artificial phenomenon, it makes SPOA stuck and runs forever for reads curation.
We will set a read depth limit / running time limit in this step in next version.
Please stay tune.

Regards,
Cheng-Kai
